<template>
  <div>
    <div id="edit" class="edit" style="margin: 5px">
      <el-row>
        <el-col span="8">
          <div>
            <el-button>
              <i class="el-icon-refresh-left"> 撤销</i>
            </el-button>
            <el-button>
              <i class="el-icon-refresh-right"> 恢复</i>
            </el-button>
            <el-button>
              <i class="el-icon-folder" @click="showAxios"> 保存</i>
            </el-button>
          </div>
        </el-col>
        <el-col span="3" offset="13">
          <div>
            <el-button>
              <i class="el-icon-plus" @click="zoomOut"></i>
            </el-button>
            <el-button>
              <i class="el-icon-minus" @click="zoomIn"></i>
            </el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <div class="graph-panel" id="graph-panel" style="margin: 10px"></div>
  </div>

</template>

<script>
import VisGraph from '../assets/js/visgraph.min.js'
// import LayoutFactory from './assets/js/visgraph—layout.min.js'

import * as axios from "axios";

export default {
  name: "GraphVue",
  components:{
    // VisGraph,
    // LayoutFactory
  },
  data(){
    return{
      visGraph : null,
      graphData: {
        nodes: [
          {
            "id":1,
            "label":"黑风山熊罴怪",
            "x":-1049,
            "y":2447,
            "size":39,
            "scale":"1.8",
            "color":"rgb(120,233,133)"
          },
          {
            "id":2,
            "label":"观世音菩萨",
            "x":-655,
            "y":2163,
            "size":39,
            "scale":"3.8",
            "color":"rgb(120,233,133)"
          },
          {
            "id":3,
            "label":"黑水河鼍怪",
            "x":-191,
            "y":3018,
            "size":39,
            "scale":"1.8",
            "color":"rgb(100,156,85)"
          },
          {
            "id":4,
            "label":"西海龙王敖闰",
            "x":-354,
            "y":2649,
            "size":39,
            "scale":"2.5",
            "color":"rgb(100,156,85)"
          },
          {
            "id":5,
            "label":"黄风大圣",
            "x":-1725,
            "y":1703,
            "size":39,
            "scale":"1.8",
            "color":"rgb(208,87,94)"
          },
          {
            "id":6,
            "label":"灵吉菩萨",
            "x":-1347,
            "y":1712,
            "size":39,
            "scale":"2.1",
            "color":"rgb(208,87,94)"
          },
          {
            "id":7,
            "label":"黄袍怪",
            "x":-407,
            "y":970,
            "size":39,
            "scale":"2.3",
            "color":"rgb(27,42,151)"
          },
          {
            "id":8,
            "label":"玉女",
            "x":-332,
            "y":584,
            "size":39,
            "scale":"2.1",
            "color":"rgb(27,42,151)"
          },
          {
            "id":9,
            "label":"二十八星宿",
            "x":-463,
            "y":1404,
            "size":39,
            "scale":"2.1",
            "color":"rgb(251,0,141)"
          },
          {
            "id":10,
            "label":"黄眉大王",
            "x":-1712,
            "y":2212,
            "size":39,
            "scale":"1.8",
            "color":"rgb(208,87,94)"
          },
          {
            "id":11,
            "label":"弥勒佛",
            "x":-1338,
            "y":2039,
            "size":39,
            "scale":"2.1",
            "color":"rgb(208,87,94)"
          },
          {
            "id":12,
            "label":"阴曹阎王",
            "x":402,
            "y":1925,
            "size":39,
            "scale":"2.5",
            "color":"rgb(135,235,33)"
          },
          {
            "id":13,
            "label":"十代冥王",
            "x":-41,
            "y":1889,
            "size":39,
            "scale":"2.1",
            "color":"rgb(251,0,141)"
          },
          {
            "id":14,
            "label":"镇元大仙",
            "x":-913,
            "y":1501,
            "size":39,
            "scale":"1.8",
            "color":"rgb(208,87,94)"
          },
          {
            "id":15,
            "label":"如来佛祖",
            "x":-1000,
            "y":1813,
            "size":39,
            "scale":"4.0",
            "color":"rgb(208,87,94)"
          },
          {
            "id":16,
            "label":"银角大王",
            "x":138,
            "y":1294,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":17,
            "label":"太上老君",
            "x":-112,
            "y":1587,
            "size":39,
            "scale":"2.7",
            "color":"rgb(251,0,141)"
          },
          {
            "id":18,
            "label":"金角大王",
            "x":240,
            "y":1452,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":19,
            "label":"通天河鱼怪",
            "x":-435,
            "y":2454,
            "size":39,
            "scale":"1.8",
            "color":"rgb(120,233,133)"
          },
          {
            "id":20,
            "label":"玉皇大帝",
            "x":-453,
            "y":1816,
            "size":39,
            "scale":"3.9",
            "color":"rgb(251,0,141)"
          },
          {
            "id":21,
            "label":"四海龙王",
            "x":-190,
            "y":2206,
            "size":39,
            "scale":"2.7",
            "color":"rgb(251,0,141)"
          },
          {
            "id":22,
            "label":"菩提祖师",
            "x":-1177,
            "y":2011,
            "size":39,
            "scale":"2.1",
            "color":"rgb(208,87,94)"
          },
          {
            "id":23,
            "label":"红孩儿",
            "x":-690,
            "y":2648,
            "size":39,
            "scale":"2.3",
            "color":"rgb(64,215,48)"
          },
          {
            "id":24,
            "label":"铁扇公主",
            "x":-943,
            "y":3001,
            "size":39,
            "scale":"1.8",
            "color":"rgb(64,215,48)"
          },
          {
            "id":25,
            "label":"牛魔王",
            "x":-627,
            "y":3028,
            "size":39,
            "scale":"1.8",
            "color":"rgb(64,215,48)"
          },
          {
            "id":26,
            "label":"百眼魔君",
            "x":-1513,
            "y":1242,
            "size":39,
            "scale":"2.1",
            "color":"rgb(208,87,94)"
          },
          {
            "id":27,
            "label":"毗蓝婆菩萨",
            "x":-1197,
            "y":1502,
            "size":39,
            "scale":"2.3",
            "color":"rgb(208,87,94)"
          },
          {
            "id":28,
            "label":"无派系",
            "x":-1828,
            "y":1008,
            "size":39,
            "scale":"2.7",
            "color":"rgb(149,117,153)"
          },
          {
            "id":29,
            "label":"白龙马",
            "x":-614,
            "y":2464,
            "size":39,
            "scale":"2.8",
            "color":"rgb(120,233,133)"
          },
          {
            "id":30,
            "label":"猪八戒",
            "x":-921,
            "y":2567,
            "size":39,
            "scale":"2.7",
            "color":"rgb(120,233,133)"
          },
          {
            "id":31,
            "label":"沙和尚",
            "x":-802,
            "y":2394,
            "size":39,
            "scale":"2.7",
            "color":"rgb(120,233,133)"
          },
          {
            "id":32,
            "label":"孙悟空",
            "x":-911,
            "y":2200,
            "size":39,
            "scale":"3.0",
            "color":"rgb(120,233,133)"
          },
          {
            "id":33,
            "label":"唐僧",
            "x":-1145,
            "y":2183,
            "size":39,
            "scale":"3.0",
            "color":"rgb(120,233,133)"
          },
          {
            "id":34,
            "label":"白鹿精",
            "x":-149,
            "y":1054,
            "size":39,
            "scale":"2.1",
            "color":"rgb(251,0,141)"
          },
          {
            "id":35,
            "label":"南极寿星",
            "x":-312,
            "y":1469,
            "size":39,
            "scale":"2.1",
            "color":"rgb(251,0,141)"
          },
          {
            "id":36,
            "label":"白骨精",
            "x":-1986,
            "y":693,
            "size":39,
            "scale":"1.8",
            "color":"rgb(149,117,153)"
          },
          {
            "id":37,
            "label":"琵琶洞蝎子精",
            "x":-2235,
            "y":1152,
            "size":39,
            "scale":"1.8",
            "color":"rgb(149,117,153)"
          },
          {
            "id":38,
            "label":"王母娘娘",
            "x":-707,
            "y":1915,
            "size":39,
            "scale":"2.7",
            "color":"rgb(251,0,141)"
          },
          {
            "id":39,
            "label":"嫦娥",
            "x":-1195,
            "y":2384,
            "size":39,
            "scale":"2.3",
            "color":"rgb(251,0,141)"
          },
          {
            "id":40,
            "label":"狮魔王",
            "x":-1753,
            "y":1981,
            "size":39,
            "scale":"1.8",
            "color":"rgb(208,87,94)"
          },
          {
            "id":41,
            "label":"文殊菩萨",
            "x":-1346,
            "y":1875,
            "size":39,
            "scale":"2.1",
            "color":"rgb(208,87,94)"
          },
          {
            "id":42,
            "label":"独角兕",
            "x":-15,
            "y":1189,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":43,
            "label":"狐狸精",
            "x":91,
            "y":733,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":44,
            "label":"杨戬",
            "x":-564,
            "y":1543,
            "size":39,
            "scale":"2.3",
            "color":"rgb(251,0,141)"
          },
          {
            "id":45,
            "label":"木吒",
            "x":-454,
            "y":2303,
            "size":39,
            "scale":"2.1",
            "color":"rgb(120,233,133)"
          },
          {
            "id":46,
            "label":"托塔天王",
            "x":-414,
            "y":2074,
            "size":39,
            "scale":"2.8",
            "color":"rgb(120,233,133)"
          },
          {
            "id":47,
            "label":"普贤菩萨",
            "x":-1033,
            "y":1407,
            "size":39,
            "scale":"2.1",
            "color":"rgb(208,87,94)"
          },
          {
            "id":48,
            "label":"昴日星官",
            "x":-676,
            "y":1723,
            "size":39,
            "scale":"2.3",
            "color":"rgb(120,233,133)"
          },
          {
            "id":49,
            "label":"摩昂太子",
            "x":-837,
            "y":2735,
            "size":39,
            "scale":"2.1",
            "color":"rgb(100,156,85)"
          },
          {
            "id":50,
            "label":"巨灵神",
            "x":-120,
            "y":2404,
            "size":39,
            "scale":"1.8",
            "color":"rgb(120,233,133)"
          },
          {
            "id":51,
            "label":"太白金星",
            "x":-222,
            "y":1940,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":52,
            "label":"李世民",
            "x":-1394,
            "y":2500,
            "size":39,
            "scale":"1.8",
            "color":"rgb(120,233,133)"
          },
          {
            "id":53,
            "label":"哪吒",
            "x":-870,
            "y":2022,
            "size":39,
            "scale":"2.3",
            "color":"rgb(120,233,133)"
          },
          {
            "id":54,
            "label":"南海龙王敖钦",
            "x":153,
            "y":2412,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":55,
            "label":"南山大王",
            "x":-2172,
            "y":919,
            "size":39,
            "scale":"1.8",
            "color":"rgb(149,117,153)"
          },
          {
            "id":56,
            "label":"北海龙王敖顺",
            "x":204,
            "y":2240,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":57,
            "label":"六耳猕猴",
            "x":-1766,
            "y":588,
            "size":39,
            "scale":"1.8",
            "color":"rgb(149,117,153)"
          },
          {
            "id":58,
            "label":"东海龙王敖广",
            "x":44,
            "y":2555,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":59,
            "label":"四大天王",
            "x":-220,
            "y":1785,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":60,
            "label":"九日翟星",
            "x":-315,
            "y":1642,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":61,
            "label":"十八罗汉",
            "x":-1195,
            "y":1699,
            "size":39,
            "scale":"1.8",
            "color":"rgb(208,87,94)"
          },
          {
            "id":62,
            "label":"八大金刚",
            "x":-1069,
            "y":1598,
            "size":39,
            "scale":"1.8",
            "color":"rgb(208,87,94)"
          },
          {
            "id":63,
            "label":"黄牙象怪",
            "x":-1139,
            "y":1042,
            "size":39,
            "scale":"1.8",
            "color":"rgb(208,87,94)"
          },
          {
            "id":64,
            "label":"金吒",
            "x":-828,
            "y":1649,
            "size":39,
            "scale":"2.1",
            "color":"rgb(120,233,133)"
          },
          {
            "id":65,
            "label":"后羿",
            "x":-1402,
            "y":2725,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":66,
            "label":"哮天犬",
            "x":-602,
            "y":1080,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          },
          {
            "id":67,
            "label":"催命判官",
            "x":766,
            "y":1945,
            "size":39,
            "scale":"1.8",
            "color":"rgb(135,235,33)"
          },
          {
            "id":68,
            "label":"白无常",
            "x":723,
            "y":1655,
            "size":39,
            "scale":"1.8",
            "color":"rgb(135,235,33)"
          },
          {
            "id":69,
            "label":"黑无常",
            "x":693,
            "y":2225,
            "size":39,
            "scale":"1.8",
            "color":"rgb(135,235,33)"
          },
          {
            "id":70,
            "label":"青牛精",
            "x":276,
            "y":1646,
            "size":39,
            "scale":"1.8",
            "color":"rgb(251,0,141)"
          }
        ],
        links: [
          {
            "source":1,
            "target":2
          },
          {
            "source":3,
            "target":4
          },
          {
            "source":5,
            "target":6
          },
          {
            "source":7,
            "target":8
          },
          {
            "source":7,
            "target":9
          },
          {
            "source":10,
            "target":11
          },
          {
            "source":12,
            "target":13
          },
          {
            "source":14,
            "target":15
          },
          {
            "source":16,
            "target":17
          },
          {
            "source":18,
            "target":17
          },
          {
            "source":19,
            "target":2
          },
          {
            "source":2,
            "target":20
          },
          {
            "source":2,
            "target":15
          },
          {
            "source":4,
            "target":21
          },
          {
            "source":22,
            "target":15
          },
          {
            "source":23,
            "target":24
          },
          {
            "source":23,
            "target":2
          },
          {
            "source":23,
            "target":25
          },
          {
            "source":26,
            "target":27
          },
          {
            "source":26,
            "target":28
          },
          {
            "source":29,
            "target":2
          },
          {
            "source":29,
            "target":4
          },
          {
            "source":29,
            "target":30
          },
          {
            "source":29,
            "target":31
          },
          {
            "source":29,
            "target":32
          },
          {
            "source":29,
            "target":33
          },
          {
            "source":34,
            "target":35
          },
          {
            "source":36,
            "target":28
          },
          {
            "source":37,
            "target":28
          },
          {
            "source":38,
            "target":20
          },
          {
            "source":38,
            "target":15
          },
          {
            "source":20,
            "target":38
          },
          {
            "source":20,
            "target":15
          },
          {
            "source":8,
            "target":7
          },
          {
            "source":30,
            "target":2
          },
          {
            "source":30,
            "target":39
          },
          {
            "source":30,
            "target":33
          },
          {
            "source":40,
            "target":41
          },
          {
            "source":42,
            "target":17
          },
          {
            "source":43,
            "target":34
          },
          {
            "source":6,
            "target":15
          },
          {
            "source":31,
            "target":2
          },
          {
            "source":31,
            "target":30
          },
          {
            "source":31,
            "target":32
          },
          {
            "source":31,
            "target":33
          },
          {
            "source":27,
            "target":15
          },
          {
            "source":44,
            "target":38
          },
          {
            "source":44,
            "target":20
          },
          {
            "source":45,
            "target":2
          },
          {
            "source":45,
            "target":46
          },
          {
            "source":47,
            "target":15
          },
          {
            "source":48,
            "target":2
          },
          {
            "source":48,
            "target":20
          },
          {
            "source":48,
            "target":27
          },
          {
            "source":41,
            "target":15
          },
          {
            "source":49,
            "target":4
          },
          {
            "source":49,
            "target":32
          },
          {
            "source":46,
            "target":2
          },
          {
            "source":46,
            "target":20
          },
          {
            "source":11,
            "target":15
          },
          {
            "source":50,
            "target":46
          },
          {
            "source":32,
            "target":2
          },
          {
            "source":32,
            "target":22
          },
          {
            "source":32,
            "target":15
          },
          {
            "source":32,
            "target":33
          },
          {
            "source":39,
            "target":38
          },
          {
            "source":51,
            "target":20
          },
          {
            "source":17,
            "target":20
          },
          {
            "source":33,
            "target":2
          },
          {
            "source":33,
            "target":52
          },
          {
            "source":33,
            "target":15
          },
          {
            "source":53,
            "target":2
          },
          {
            "source":53,
            "target":46
          },
          {
            "source":53,
            "target":15
          },
          {
            "source":54,
            "target":21
          },
          {
            "source":35,
            "target":20
          },
          {
            "source":55,
            "target":28
          },
          {
            "source":56,
            "target":21
          },
          {
            "source":57,
            "target":28
          },
          {
            "source":58,
            "target":21
          },
          {
            "source":59,
            "target":20
          },
          {
            "source":9,
            "target":20
          },
          {
            "source":60,
            "target":20
          },
          {
            "source":13,
            "target":20
          },
          {
            "source":61,
            "target":15
          },
          {
            "source":62,
            "target":15
          },
          {
            "source":63,
            "target":47
          },
          {
            "source":64,
            "target":46
          },
          {
            "source":64,
            "target":15
          },
          {
            "source":65,
            "target":39
          },
          {
            "source":66,
            "target":44
          },
          {
            "source":67,
            "target":12
          },
          {
            "source":68,
            "target":12
          },
          {
            "source":69,
            "target":12
          },
          {
            "source":70,
            "target":17
          },
          {
            "source":21,
            "target":20
          }
        ]
      }
    }
  },
  mounted(){
    this.visGraph = new VisGraph(document.getElementById('graph-panel'));//初始化绘图客户端
    this.visGraph.drawData(this.graphData);//绘制图完成
  },
  methods:{
    showAxios: function (){
      console.log('clicked')
      axios.get('http://localhost:5000/graph-data')
          .then(function (response) {
            console.log(response);
          })
          .catch(function (error) {
            console.log(error);
          });
    },
    zoomOut: function (){
      // console.log('放大')
      this.visGraph.setZoom('zoomOut')
    },
    zoomIn: function (){
      // console.log('缩小')
      this.visGraph.setZoom('zoomIn')
    }
  }
}
</script>

<style scoped>
.graph-panel{
  width: 1000px;
  height: 600px;
}
</style>